### PR TITLE
feat: disable install recommends and upgrade

### PR DESCRIPTION
**Pull request by ViceIce**
ref renovatebot/renovate#5003

merge #18 before and rebase to see if it's working

### CODE REVIEW

**Comment by rarkins** [comment]
It appears that Docker Hub is building every feature branch:

image

image

**Comment by rarkins** [comment]
Maybe we don't need GitHub Actions?

**Comment by ViceIce** [comment]
I think github is more reliable 😅

**Comment by rarkins** [comment]
OK, we can have both. How to see it here? Needs a rebase?

**Comment by ViceIce** [comment]
don't think so, as docker hub alrready build successful

**Comment by rarkins** [comment]
I'm not seeing it under checks, although it seems to have run

**Comment by ViceIce** [comment]
maybe you need a page reload

**Comment by rarkins** [comment]
image

What do you see?

**Comment by ViceIce** [comment]
you mean the github workflow, for it to run we need to rebase

**Comment by rarkins** [comment]
Now it's showing

**Comment by ViceIce** [comment]
and done 😅

**Pull request merged**
